import { Geist, Geist_Mono } from "next/font/google";
import "./styles.css"
import {Inter} from "next/font/google"

const inter = Inter({
  subsets: ["latin"]
});

export const metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className=''
      >
        {children}
      </body>
    </html>
  );
}
